### ISSUE TITLE
Distance check box on SRT turning back on

### ISSUE THREAD

**Issue by rotorgeeks** [avsaase/walksnail-osd-tool#17]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Software version

0.1.0  bd788b6

### What operating system are you using?

Windows 10

### What problem did you encounter?

When previously unchecked, the checkbox for "Distance" in SRT data gets checked each time a new video file is loaded

**Comment by avsaase** [comment]
This is working as intended because I wanted to avoid having to tick the distance box when loading a file with distances after loading one without. But I now see how it can be annoying. This behavior is changed in https://github.com/avsaase/walksnail-osd-tool/commit/f6660c562d52f3d60e709a7680ab3cb8dae72627. You can download the latest build with this change in about 15 minutes from this link: https://nightly.link/avsaase/walksnail-osd-tool/workflows/release.yaml/master/walksnail-osd-tool-all-platforms.zip.

**Comment by rotorgeeks** [comment]
Updated version is great, thank you!  Do I dare I put in a request for batch capability?

**Comment by avsaase** [comment]
> Do I dare I put in a request for batch capability?

It's planned but I please create a feature request with a description how you want it to work.
